# **Structured Data Assignment**

**Problem 1**

In [287]:
import pandas as pd
import numpy as np
#To ignore warnings
import warnings
warnings.filterwarnings("ignore")

#Train data

In [288]:
df = pd.read_parquet("/content/train.parquet")

In [289]:
df.head()

                            Patient-Uid       Date           Incident
0  a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2019-03-09  PRIMARY_DIAGNOSIS
1  a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f 2015-05-16  PRIMARY_DIAGNOSIS
3  a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f 2018-01-30     SYMPTOM_TYPE_0
4  a0dc950b-1c7c-11ec-b6ec-16262ee38c7f 2015-04-22        DRUG_TYPE_0
8  a0dc9543-1c7c-11ec-bb63-16262ee38c7f 2016-06-18        DRUG_TYPE_1

In [290]:
df.describe()

                                 Patient-Uid                 Date     Incident
count                                3220868              3220868      3220868
unique                                 27033                 1977           57
top     a0ddfd2c-1c7c-11ec-876d-16262ee38c7f  2019-05-21 00:00:00  DRUG_TYPE_6
freq                                    1645                 3678       561934
first                                    NaN  2015-04-07 00:00:00          NaN
last                                     NaN  2020-09-03 00:00:00          NaN

**Data cleaning**

In [291]:
df = df.dropna()

In [292]:
df = df.drop_duplicates()

In [293]:
df = df.drop("Date", axis=1)

In [294]:
df.head()

                            Patient-Uid           Incident
0  a0db1e73-1c7c-11ec-ae39-16262ee38c7f  PRIMARY_DIAGNOSIS
1  a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f  PRIMARY_DIAGNOSIS
3  a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f     SYMPTOM_TYPE_0
4  a0dc950b-1c7c-11ec-b6ec-16262ee38c7f        DRUG_TYPE_0
8  a0dc9543-1c7c-11ec-bb63-16262ee38c7f        DRUG_TYPE_1

**Encoding**

In [295]:
import pandas as pd


# One-hot encode the Incident column
one_hot = pd.get_dummies(df['Incident'])

# Concatenate the one-hot encoded column with the original DataFrame
df = pd.concat([df, one_hot], axis=1)

# Group the incidents by Patient-Uid and sum the one-hot encoded columns
grouped = df.groupby('Patient-Uid').sum()

# Display the resulting DataFrame
grouped

,DRUG_TYPE_0,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
Patient-Uid,,,,,,,,,,,,,,,,,,,,,
a0db1e73-1c7c-11ec-ae39-16262ee38c7f,29,0,0,1,0,0,0,0,0,0,...,1,0,0,0,10,2,0,0,0,0
a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,8,27,0,0,0,0,0,0,0,0,...,0,0,0,0,1,4,0,0,0,0
a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,6,7,0,10,0,0,0,0,0,0,...,0,0,0,0,3,2,0,0,0,0
a0dc950b-1c7c-11ec-b6ec-16262ee38c7f,15,42,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a0dc9543-1c7c-11ec-bb63-16262ee38c7f,2,45,0,24,0,0,0,0,0,0,...,5,6,0,0,9,27,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a0f0d4c5-1c7c-11ec-bfec-16262ee38c7f,48,9,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
a0f0d4f4-1c7c-11ec-b144-16262ee38c7f,17,23,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
a0f0d523-1c7c-11ec-89d2-16262ee38c7f,8,48,0,3,0,0,0,0,0,0,...,0,0,0,3,0,3,0,0,0,0
a0f0d553-1c7c-11ec-a70a-16262ee38c7f,7,44,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
a0f0d582-1c7c-11ec-a6c1-16262ee38c7f,3,35,1,0,0,0,0,0,0,0,...,0,0,0,3,0,4,1,0,0,0

In [296]:
grouped['TARGET DRUG'] = grouped['TARGET DRUG'].apply(lambda x: 0 if x == 0 else 1)
grouped

,DRUG_TYPE_0,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
Patient-Uid,,,,,,,,,,,,,,,,,,,,,
a0db1e73-1c7c-11ec-ae39-16262ee38c7f,29,0,0,1,0,0,0,0,0,0,...,1,0,0,0,10,2,0,0,0,0
a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,8,27,0,0,0,0,0,0,0,0,...,0,0,0,0,1,4,0,0,0,0
a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,6,7,0,10,0,0,0,0,0,0,...,0,0,0,0,3,2,0,0,0,0
a0dc950b-1c7c-11ec-b6ec-16262ee38c7f,15,42,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a0dc9543-1c7c-11ec-bb63-16262ee38c7f,2,45,0,24,0,0,0,0,0,0,...,5,6,0,0,9,27,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a0f0d4c5-1c7c-11ec-bfec-16262ee38c7f,48,9,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
a0f0d4f4-1c7c-11ec-b144-16262ee38c7f,17,23,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
a0f0d523-1c7c-11ec-89d2-16262ee38c7f,8,48,0,3,0,0,0,0,0,0,...,0,0,0,1,0,3,0,0,0,0
a0f0d553-1c7c-11ec-a70a-16262ee38c7f,7,44,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
a0f0d582-1c7c-11ec-a6c1-16262ee38c7f,3,35,1,0,0,0,0,0,0,0,...,0,0,0,1,0,4,1,0,0,0

use grouped for train

#Test data

In [297]:
df1 = pd.read_parquet("/content/test.parquet")

In [298]:
df1.describe()

                                 Patient-Uid                 Date     Incident
count                                1065524              1065524      1065524
unique                                 11482                 1947           55
top     a0faa6ed-1c7c-11ec-8f6f-16262ee38c7f  2018-03-13 00:00:00  DRUG_TYPE_6
freq                                    1236                 1139       192292
first                                    NaN  2015-04-07 00:00:00          NaN
last                                     NaN  2020-08-04 00:00:00          NaN

In [299]:
df1

                                  Patient-Uid       Date        Incident
0        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08  SYMPTOM_TYPE_0
1        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-17     DRUG_TYPE_0
2        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01     DRUG_TYPE_2
3        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-12-05     DRUG_TYPE_1
4        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-11-04  SYMPTOM_TYPE_0
...                                       ...        ...             ...
1372854  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2017-05-11    DRUG_TYPE_13
1372856  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2018-08-22     DRUG_TYPE_2
1372857  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2017-02-04     DRUG_TYPE_2
1372858  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2017-09-25     DRUG_TYPE_8
1372859  a10272c9-1c7c-11ec-b3ce-16262ee38c7f 2017-05-19     DRUG_TYPE_7

[1065524 rows x 3 columns]

In [300]:
df1=df1.dropna()

In [301]:
df1 = df1.drop_duplicates()

In [302]:
df1 = df1.drop("Date", axis=1)

In [303]:
df1

                                  Patient-Uid        Incident
0        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f  SYMPTOM_TYPE_0
1        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f     DRUG_TYPE_0
2        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f     DRUG_TYPE_2
3        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f     DRUG_TYPE_1
4        a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f  SYMPTOM_TYPE_0
...                                       ...             ...
1372854  a10272c9-1c7c-11ec-b3ce-16262ee38c7f    DRUG_TYPE_13
1372856  a10272c9-1c7c-11ec-b3ce-16262ee38c7f     DRUG_TYPE_2
1372857  a10272c9-1c7c-11ec-b3ce-16262ee38c7f     DRUG_TYPE_2
1372858  a10272c9-1c7c-11ec-b3ce-16262ee38c7f     DRUG_TYPE_8
1372859  a10272c9-1c7c-11ec-b3ce-16262ee38c7f     DRUG_TYPE_7

[1053424 rows x 2 columns]

In [304]:
import pandas as pd


# One-hot encode the Incident column
one_hot = pd.get_dummies(df1['Incident'])

# Concatenate the one-hot encoded column with the original DataFrame
df1 = pd.concat([df1, one_hot], axis=1)

# Group the incidents by Patient-Uid and sum the one-hot encoded columns
test_data = df1.groupby('Patient-Uid').sum()

# Display the resulting DataFrame
test_data

,DRUG_TYPE_0,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
Patient-Uid,,,,,,,,,,,,,,,,,,,,,
a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f,8,3,0,1,0,0,0,0,0,0,...,3,0,0,0,2,0,0,0,0,0
a0f9e9f9-1c7c-11ec-b565-16262ee38c7f,2,30,0,0,0,0,0,9,0,0,...,2,0,0,0,0,0,0,1,0,0
a0f9ea43-1c7c-11ec-aa10-16262ee38c7f,4,33,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,0
a0f9ea7c-1c7c-11ec-af15-16262ee38c7f,2,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
a0f9eab1-1c7c-11ec-a732-16262ee38c7f,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a102720c-1c7c-11ec-bd9a-16262ee38c7f,33,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a102723c-1c7c-11ec-9f80-16262ee38c7f,4,6,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
a102726b-1c7c-11ec-bfbf-16262ee38c7f,14,5,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a102729b-1c7c-11ec-86ba-16262ee38c7f,5,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
a10272c9-1c7c-11ec-b3ce-16262ee38c7f,1,0,0,0,0,30,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [305]:
# add a new column 'TARGET DRUG' to the DataFrame with default values of 0
test_data['TARGET DRUG'] = 0
test_data['DRUG_TYPE_18'] =0

In [306]:
test_pred=test_data.drop('TARGET DRUG',axis=1).values

In [307]:
X=grouped.drop('TARGET DRUG',axis=1).values
y=grouped['TARGET DRUG'].values

 Model

In [308]:
import pandas as pd
from sklearn.model_selection import train_test_split
# split train data into train and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

In [309]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score,f1_score
rf = RandomForestClassifier(n_estimators= 100, max_depth = 16, max_features='sqrt')
rf.fit(X_train, y_train)
predictions = rf.predict(X_val)
print("Training Accuracy :",rf.score(X_train,y_train))
print("Testing Accuracy :",rf.score(X_val,y_val))
print("F1 Score :", f1_score(y_val,predictions))
print("ROC AUC Score :", roc_auc_score(y_val,predictions))

Training Accuracy : 0.9407657449366503
Testing Accuracy : 0.8071019049380432
F1 Score : 0.7079249509941195
ROC AUC Score : 0.7746539467750836

In [310]:
predict = rf.predict(test_pred)

In [311]:
predict

array([0, 0, 0, ..., 0, 0, 0])

In [312]:
df3 = pd.DataFrame(predict)
df3

       0
0      0
1      0
2      0
3      0
4      0
...   ..
11477  0
11478  0
11479  0
11480  0
11481  0

[11482 rows x 1 columns]

In [313]:
df3[0].unique()

array([0, 1])

In [314]:
df3 = df3.rename(columns={0: 'predict'})
df3

       predict
0            0
1            0
2            0
3            0
4            0
...        ...
11477        0
11478        0
11479        0
11480        0
11481        0

[11482 rows x 1 columns]

In [315]:
test_data = test_data.reset_index()

In [316]:
final_data = pd.concat([test_data["Patient-Uid"], df3["predict"]], axis=1)
final_data

                                Patient-Uid  predict
0      a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f        0
1      a0f9e9f9-1c7c-11ec-b565-16262ee38c7f        0
2      a0f9ea43-1c7c-11ec-aa10-16262ee38c7f        0
3      a0f9ea7c-1c7c-11ec-af15-16262ee38c7f        0
4      a0f9eab1-1c7c-11ec-a732-16262ee38c7f        0
...                                     ...      ...
11477  a102720c-1c7c-11ec-bd9a-16262ee38c7f        0
11478  a102723c-1c7c-11ec-9f80-16262ee38c7f        0
11479  a102726b-1c7c-11ec-bfbf-16262ee38c7f        0
11480  a102729b-1c7c-11ec-86ba-16262ee38c7f        0
11481  a10272c9-1c7c-11ec-b3ce-16262ee38c7f        0

[11482 rows x 2 columns]

patients who needs traget drug

In [317]:
fd=final_data[final_data["predict"]==1]
fd

                                Patient-Uid  predict
130    a0fa02fd-1c7c-11ec-86c6-16262ee38c7f        1
213    a0fa12d2-1c7c-11ec-83fe-16262ee38c7f        1
314    a0fa25f4-1c7c-11ec-a5c8-16262ee38c7f        1
358    a0fa2e65-1c7c-11ec-a08d-16262ee38c7f        1
592    a0fa5a9b-1c7c-11ec-8db4-16262ee38c7f        1
949    a0fa9ecc-1c7c-11ec-a9a0-16262ee38c7f        1
1805   a0fb4225-1c7c-11ec-9e36-16262ee38c7f        1
2389   a0fbb144-1c7c-11ec-80e9-16262ee38c7f        1
2407   a0fbb4bd-1c7c-11ec-be78-16262ee38c7f        1
3062   a0fc32c3-1c7c-11ec-a0b4-16262ee38c7f        1
4168   a0fd03e8-1c7c-11ec-92d0-16262ee38c7f        1
4496   a0fd4205-1c7c-11ec-8bf9-16262ee38c7f        1
5485   a0fdff8c-1c7c-11ec-b8f0-16262ee38c7f        1
7605   a0ff8f68-1c7c-11ec-b6b3-16262ee38c7f        1
7636   a0ff9544-1c7c-11ec-9d49-16262ee38c7f        1
7656   a0ff9915-1c7c-11ec-9024-16262ee38c7f        1
7742   a0ffa95e-1c7c-11ec-918c-16262ee38c7f        1
7743   a0ffa98e-1c7c-11ec-827e-16262ee38c7f        1
7770   a0ffae97-1c7c-11ec-8f4c-16262ee38c7f        1
7875   a0ffc274-1c7c-11ec-a149-16262ee38c7f        1
8157   a0fff7ad-1c7c-11ec-8594-16262ee38c7f        1
8233   a1000664-1c7c-11ec-a575-16262ee38c7f        1
8293   a10011d0-1c7c-11ec-8a16-16262ee38c7f        1
8305   a100140e-1c7c-11ec-b0c1-16262ee38c7f        1
8312   a100155c-1c7c-11ec-93cc-16262ee38c7f        1
8319   a10016aa-1c7c-11ec-aaee-16262ee38c7f        1
8405   a10026e7-1c7c-11ec-a397-16262ee38c7f        1
8473   a10033c8-1c7c-11ec-8fee-16262ee38c7f        1
8526   a1003dc2-1c7c-11ec-9ff3-16262ee38c7f        1
8593   a1004a70-1c7c-11ec-a4ad-16262ee38c7f        1
8856   a1007c1f-1c7c-11ec-9bb5-16262ee38c7f        1
8888   a1008233-1c7c-11ec-bf66-16262ee38c7f        1
8891   a10082c1-1c7c-11ec-87bb-16262ee38c7f        1
8925   a100892d-1c7c-11ec-aa64-16262ee38c7f        1
8935   a1008b0d-1c7c-11ec-a940-16262ee38c7f        1
9067   a100a471-1c7c-11ec-bfe4-16262ee38c7f        1
9087   a100a844-1c7c-11ec-849d-16262ee38c7f        1
9117   a100ade7-1c7c-11ec-a8e9-16262ee38c7f        1
9155   a100b51b-1c7c-11ec-88ff-16262ee38c7f        1
9385   a100e0d4-1c7c-11ec-83dc-16262ee38c7f        1
9604   a10109bb-1c7c-11ec-b379-16262ee38c7f        1
9619   a1010c84-1c7c-11ec-b0fe-16262ee38c7f        1
9683   a101187a-1c7c-11ec-9c5d-16262ee38c7f        1
9944   a10149b1-1c7c-11ec-a0b8-16262ee38c7f        1
10094  a10165c7-1c7c-11ec-acac-16262ee38c7f        1
10306  a1018d58-1c7c-11ec-a6e0-16262ee38c7f        1
10314  a1018ed3-1c7c-11ec-ab1a-16262ee38c7f        1
10496  a101b0e1-1c7c-11ec-83a0-16262ee38c7f        1
10553  a101bba0-1c7c-11ec-bc13-16262ee38c7f        1
10607  a101c5b7-1c7c-11ec-b29f-16262ee38c7f        1
10876  a101f87f-1c7c-11ec-9fcb-16262ee38c7f        1
10980  a102146e-1c7c-11ec-beb7-16262ee38c7f        1

In [319]:
#save the final_submission file
final_submission = final_data[['Patient-Uid', 'predict']].rename(columns={'predict': 'label'})
final_submission.to_csv("final_submission.csv", index=False)